spring:
  cloud:
    stream:
      bindings:
        qlqProducer:
          destination: MQ_SPRING_STREAM_BEGIN
        qlqConsumer:
          destination: MQ_SPRING_STREAM_BEGIN
          group: QLQ_PROVIDER
  zipkin:
    base-url: http://127.0.0.1:9411
  application:
    name: mask-order
  rabbitmq:
    password: guest
    port: 5672
    host: 127.0.0.1
    username: guest
server:
  port: 8085
management:
  security:
    enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
logging:
  config: classpath:log4j2.xml
