spring:
  cloud:
    stream:
      bindings:
        qlqProducer:
          destination: MQ_SPRING_STREAM_BEGIN
        qlqConsumer:
          destination: MQ_SPRING_STREAM_BEGIN
          group: QLQ_PROVIDER
  zipkin:
    base-url: http://127.0.0.1:9411
  application:
    name: mask-order
  rabbitmq:
    password: guest
    port: 5672
    host: 127.0.0.1
    username: guest
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mask-order?useUnicode=true&characterEncoding=utf8&verifyServerCertificate=false&useSSL=false&useOldAliasMetadataBehavior=true
    username: root
    password: root
    druid:
        # 连接池启动时创建的连接数量的初始值
        initial-size: 5
        # 最小空闲值，当空闲的连接数少于阀值时，连接池就会去预申请连接
        min-idle: 5
        # 连接池的最大值，同一时间可以从连接池分配的最多连接数量
        max-active: 20
        # 配置获取连接等待超时的时间
        max-wait: 60000
        # 配置监控统计拦截的filters，用于监控SQL，wall用于防火墙
        filter: stat,wall
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
server:
  port: 8085
#management:
#  security:
#    enabled: false
mybatis:
  mapper-locations: classpath:mapper/*.xml
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
logging:
  config: classpath:log4j2.xml
tx-lcn:
  client:
    manager-address: 127.0.0.1:8070