
spring:
  application:
    name: mask-gateway
  cloud:
    loadbalancer:
      retry:
        enabled: true

server:
  port: 8084
eureka:
  client:
    service-url:
      default-zone: http://127.0.0.1:8082/eureka
zuul:
  # 禁止服务自动添加
  ignored-services: '*'
  routes:
    api-a:
      path: /user/**
      service-id: mask-user
    api-b:
      path: /order/**
      service-id: mask-order
  # 开启重试功能
  retryable: true
#    # 在zuul和服务间增加feign只会增加通讯消耗，并不推荐
#    api-c:
#      path: /feign/**
#      # 由网关分发到feign，再经feign负载均衡
#      service-id: mask-feign